### ISSUE TITLE
server not found

### ISSUE THREAD

**Issue by SACViper** [flathub/com.skype.Client#75]
As package no longer there 

Error: While downloading https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.50.0.38_amd64.deb: Server returned status 404: Not Found
error: Failed to install com.skype.Client: While downloading https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.50.0.38_amd64.deb: Server returned status 404: Not Found

**Comment by ghostry** [comment]
https://repo.skype.com/deb/pool/main/s/skypeforlinux/

**Comment by LeandroStanger** [comment]
@ramcq @develop7 Could help?

**Comment by develop7** [comment]
I'm not a maintainer. Doing `snap install --classic skype` in the meantime.

**Comment by develop7** [comment]
should work now, as #74 has been merged

**Comment by dirkdavidis** [comment]
tried on fedora 30 right now ... still not working ... 

Error: While downloading https://repo.skype.com/deb/pool/main/s/skypeforlinux/skypeforlinux_8.50.0.38_amd64.deb: Server returned status 404: Not Found

**Comment by develop7** [comment]
@dirkdavidis yup https://flathub.org/builds/#/builders/32/builds/10046 seems unpublished yet

**Comment by ramcq** [comment]
Has anyone tested it? I'm worried that it will just be broken because of #70, which means basically now that the old 8.50.0.38 version has been removed from the Skype server, we don't have a version that we can both install and run under a Flatpak any longer.

**Comment by ramcq** [comment]
It doesn't work, I've deleted it. https://flathub.org/builds/#/builders/53/builds/5556 At least then people who have it installed don't get a broken upgrade. We need a workaround for #70. At a guess, we might be able to patch the .asar to disable sandboxing?

**Comment by ramcq** [comment]
Fixed by #74 and #77
